# The URL the site will be built for
base_url = "https://maxluoxiii.github.io"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

generate_feed = true

title = "Maxiwell Luo"
description = "Welcome to the personal website/blog of Maxiwell Luo. Look around at what I'm working on and read some of my random thoughts."

default_language = "en"

theme = "solar-theme-zola"

taxonomies = [
    { name = "year", feed = true },
    { name = "topics", feed = true }
]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "solarized-dark"

[extra]
# Put all your custom variables here
# solarized
site_menus = [
    {url = "/blog", name = "Posts"},
    {url = "https://github.com/maxluoXIII/resume/blob/master/Resume.pdf", name = "Resume"},
    {url = "/about", name = "About"},
]

github = "maxluoxiii"
twitter = "maxXIII13"

solarized_theme = "solarized-dark"

[extra.author]
name = "Maxiwell Luo"
image = "/real_me_square.jpg"
bio = "Extraordinarily ordinary"